name = "GenomicCoordinates"
uuid = "ba2eccb5-91b3-48f8-94f3-77bebdceebef"
authors = ["Peter Arndt <arndt@molgen.mpg.de> and contributors"]
version = "0.1.3"

[deps]
Intervals = "d8418881-c3e1-53bb-8760-2df7ec849ed5"

[compat]
Intervals = "1.10.0"
julia = "1.10"
